import { ClientInfo, Product, FormStep, ActivityLevel, Gender, DietType, MealRegularity, WaterIntake, ExerciseFrequency, SleepQuality, AdminContact } from './types';

export const initialClientInfo: ClientInfo = {
  name: '',
  age: '',
  gender: '',
  phone: '',
  email: '',
  occupation: '',
  activityLevel: '',
  mainGoal: '',
  priorityGoalDetails: '',
  dietType: '',
  customDietType: '',
  mealRegularity: '',
  waterIntake: '',
  exerciseFrequency: '',
  exerciseType: '',
  sleepHours: '',
  sleepQuality: '',
  commonSymptoms: [],
  medicalConditions: '',
  currentMedications: '',
  additionalInfo: '',
};

export const HEALTH_GOALS: string[] = [
  'Anti-Edad',
  'Control de Peso',
  'Desintoxicación y Limpieza',
  'Energía y Vitalidad',
  'Gastronómica y Nutrición',
  'Rendimiento Deportivo',
  'Salud Articular',
  'Salud Digestiva',
  'Salud Femenina',
  'Salud Inmunológica',
  'Vigor Mental',
];


export const ACTIVITY_LEVELS: ActivityLevel[] = Object.values(ActivityLevel);
export const GENDERS: Gender[] = Object.values(Gender);
export const DIET_TYPES: DietType[] = Object.values(DietType);
export const MEAL_REGULARITIES: MealRegularity[] = Object.values(MealRegularity);
export const WATER_INTAKES: WaterIntake[] = Object.values(WaterIntake);
export const EXERCISE_FREQUENCIES: ExerciseFrequency[] = Object.values(ExerciseFrequency);
export const SLEEP_QUALITIES: SleepQuality[] = Object.values(SleepQuality);


export const SYMPTOM_OPTIONS: string[] = [
  'Fatiga o falta de energía',
  'Problemas digestivos (hinchazón, acidez, estreñimiento)',
  'Estrés, ansiedad o mal humor',
  'Defensas bajas / Enfermedades frecuentes',
  'Dolores articulares o musculares',
  'Dificultad para concentrarse o neblina mental',
  'Problemas de piel, cabello o uñas frágiles',
  'Antojos de dulces o comida chatarra',
  'Molestias del ciclo menstrual',
  'Bochornos o síntomas de menopausia',
  'Dificultad para dormir o sueño no reparador',
  'Retención de líquidos',
  'Aumento de peso o dificultad para perderlo',
  'Problemas de circulación',
  'Libido bajo o falta de vigor',
];

export const ADMIN_CONTACT_INFO: AdminContact = {
  name: 'Ing. Alexandra Campos',
  phone: '0996480402',
};

// =================================================================================
// PRODUCT DATABASE
// =================================================================================
// INSTRUCCIÓN PARA EL USUARIO:
// Las imágenes deben estar en la carpeta `public/assets/images/`.
// Los videos deben estar en la carpeta `public/assets/videos/`.
// Los nombres de archivo deben coincidir con el 'id' del producto. Ej: 'beauty_in.png', 'beauty_in.mp4'
// =================================================================================

export const PRODUCTS: Product[] = [
  // LÍNEA ANTI-EDAD
  {
    id: 'beauty_in',
    name: 'Beauty In',
    price: 51.30,
    points: 25,
    category: 'Anti-Edad',
    description: 'Delicioso refresco de colágeno bioactivo para nutrir y rejuvenecer la piel desde adentro.',
    benefits: ['Estimula la producción de colágeno y elastina.', 'Trabaja en sinergia con antioxidantes y vitaminas.', 'Promueve una piel rejuvenecida, más firme y elástica.', 'Fortalece cabello y uñas.'],
    keyIngredients: ['Péptidos de Colágeno Bioactivo', 'Antioxidantes', 'Vitaminas'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua, preferiblemente por la noche.',
    expectedResults: 'Mejora la apariencia y salud de la piel, cabello y uñas, resultando en un aspecto más juvenil.',
    imageUrl: '/assets/images/beauty_in.jpeg',
    videoUrl: '/assets/videos/beauty_in.mp4',
    tags: ['belleza', 'piel', 'cabello', 'uñas', 'colágeno', 'antienvejecimiento', 'anti-edad', 'rejuvenecer', 'elastina'],
  },
  {
    id: 'youth_elixir',
    name: 'Youth Elixir',
    price: 41.00,
    points: 20,
    category: 'Anti-Edad',
    description: 'Combinación natural de aminoácidos con antioxidantes para nutrir la glándula pituitaria y segregar la hormona de la juventud.',
    benefits: ['Combate los efectos del envejecimiento.', 'Reduce los radicales libres.', 'Mejora la calidad del sueño y la vitalidad.', 'Aumenta la elasticidad de la piel.'],
    keyIngredients: ['Aminoácidos', 'Resveratrol', 'Extracto de la uva del vino', 'Super frutas como blueberries, sauco y amalaki'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua, preferiblemente antes de dormir.',
    expectedResults: 'Mayor vitalidad y energía, piel más elástica y una mejor calidad del sueño reparador.',
    imageUrl: '/assets/images/youth_elixir.png',
    videoUrl: '/assets/videos/youth_elixir.mp4',
    tags: ['anti-edad', 'antienvejecimiento', 'juventud', 'hgh', 'sueño', 'vitalidad', 'resveratrol', 'antioxidantes', 'piel'],
  },

  // LÍNEA VIGOR MENTAL (y relacionadas)
  {
    id: 'golden_flx',
    name: 'Golden FLX',
    price: 45.15,
    points: 22,
    category: 'Salud Articular',
    description: 'Delicioso té de especias con leche de coco, a base de cúrcuma orgánica certificada de efecto antioxidante y protector.',
    benefits: ['Mejora la flexibilidad de las articulaciones.', 'Protege las articulaciones del daño.', 'Efecto antioxidante y protector.', 'Controla procesos oxidativos.'],
    keyIngredients: ['Cúrcuma Orgánica', 'Jengibre', 'Cardamomo', 'Pimienta Negra', 'Leche de Coco'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua caliente.',
    expectedResults: 'Mejora en el confort y flexibilidad articular, ayudando a mantener la movilidad.',
    imageUrl: '/assets/images/golden_flx.png',
    videoUrl: '/assets/videos/golden_flx.mp4',
    tags: ['articulaciones', 'flexibilidad', 'dolor articular', 'antioxidante', 'cúrcuma', 'jengibre', 'antiinflamatorio'],
  },
  {
    id: 'passion',
    name: 'Passion',
    price: 41.00,
    points: 20,
    category: 'Energía y Vitalidad',
    description: 'Deliciosa bebida de Guaraná y Jalea Real, creada por Fuxion para favorecer el vigor sexual e incrementar la libido y la energía.',
    benefits: ['Favorece el vigor sexual.', 'Incrementa la libido y el nivel de energía.', 'Ayuda con problemas de circulación e hipertensión.'],
    keyIngredients: ['Guaraná', 'Jalea Real', 'Aminoácidos (L-arginina)'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua, en cualquier momento.',
    expectedResults: 'Aumento del vigor, la libido y la energía general del cuerpo.',
    imageUrl: '/assets/images/passion.png',
    videoUrl: '/assets/videos/passion.mp4',
    tags: ['vigor', 'libido', 'energía', 'circulación', 'hipertensión', 'sexual', 'pareja', 'pasión'],
  },
  {
    id: 'probal',
    name: 'Probal',
    price: 51.30,
    points: 25,
    category: 'Salud Femenina',
    description: 'Delicioso té herbal que combina aminoácidos, extractos vegetales, vitaminas y minerales para ayudar a equilibrar los desbalances propios de la menopausia y el periodo menstrual.',
    benefits: ['Ayuda a equilibrar desbalances hormonales.', 'Alivia molestias del periodo menstrual.', 'Controla síntomas de la menopausia como bochornos y cambios de humor.'],
    keyIngredients: ['Aminoácidos', 'Extractos Vegetales', 'Vitaminas', 'Minerales'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua.',
    expectedResults: 'Mayor bienestar y equilibrio durante el ciclo menstrual y la menopausia.',
    imageUrl: '/assets/images/probal.png',
    videoUrl: '/assets/videos/probal.mp4',
    tags: ['salud femenina', 'hormonal', 'menopausia', 'bochornos', 'periodo', 'menstrual', 'mujer'],
  },
  {
    id: 'on',
    name: 'ON',
    price: 41.00,
    points: 20,
    category: 'Vigor Mental',
    description: 'Deliciosa bebida nutritiva que ayuda a activar tu mente y mantenerla alerta, a base de aminoácidos y Gaba, con Yerba Mate y Acai Berry.',
    benefits: ['Activa la mente y la mantiene alerta.', 'Mejora la función cognitiva.', 'Proporciona energía mental sostenida.', 'Disipa la sensación de fatiga mental.'],
    keyIngredients: ['Aminoácidos', 'GABA', 'Yerba Mate', 'Acai Berry', 'Vitaminas', 'Minerales'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua, especialmente cuando se requiera concentración.',
    expectedResults: 'Mente más clara y alerta, mejor enfoque y rendimiento cognitivo.',
    imageUrl: '/assets/images/on.png',
    videoUrl: '/assets/videos/on.mp4',
    tags: ['vigor mental', 'concentración', 'enfoque', 'alerta', 'cerebro', 'estudio', 'trabajo', 'neblina mental'],
  },
  {
    id: 'no_stress',
    name: 'No Stress',
    price: 41.00,
    points: 20,
    category: 'Vigor Mental',
    description: 'Deliciosa bebida nutritiva a base de aminoácidos esenciales que contribuyen a mantener la función mental y el enfoque en condiciones de presión.',
    benefits: ['Ayuda a mantener la sensación de equilibrio bajo condiciones de presión.', 'Optimiza los procesos cognitivos naturales.', 'Ayuda a reducir el estrés y la ansiedad.', 'Promueve la relajación sin producir somnolencia.'],
    keyIngredients: ['Aminoácidos Esenciales', 'Triptófano', 'L-Teanina', 'GABA'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua, especialmente en momentos de estrés.',
    expectedResults: 'Sensación de calma y control, mejor manejo del estrés y la ansiedad.',
    imageUrl: '/assets/images/no_stress.png',
    videoUrl: '/assets/videos/no_stress.mp4',
    tags: ['estrés', 'ansiedad', 'calma', 'relajación', 'equilibrio', 'presión', 'mal humor', 'dormir'],
  },

  // LÍNEA SPORT
  {
    id: 'pre_sport',
    name: 'Pre Sport',
    price: 45.15,
    points: 22,
    category: 'Rendimiento Deportivo',
    description: 'Bebida isotónica, rehidratante y energizante natural que prepara el cuerpo para la actividad deportiva intensa.',
    benefits: ['Prepara el cuerpo para el ejercicio.', 'Mejora el rendimiento durante el ejercicio.', 'Aumenta la resistencia.', 'Mantiene la hidratación.'],
    keyIngredients: ['Aminoácidos (Citrulina, Creatina)', 'Sales Rehidratantes', 'Hierba Mate'],
    suggestedUsage: 'Tomar 1 stick disuelto en agua 15-30 minutos antes del ejercicio.',
    expectedResults: 'Mayor energía, resistencia y concentración durante la actividad física.',
    imageUrl: '/assets/images/pre_sport.png',
    videoUrl: '/assets/videos/pre_sport.mp4',
    tags: ['deporte', 'rendimiento deportivo', 'pre-entreno', 'energía', 'resistencia', 'hidratación', 'ejercicio'],
  },
  {
    id: 'post_sport',
    name: 'Post Sport',
    price: 45.15,
    points: 22,
    category: 'Rendimiento Deportivo',
    description: 'Bebida deportiva a base de aminoácidos, agua de coco y antioxidantes que ayudan a la recuperación del cuerpo después del ejercicio.',
    benefits: ['Acelera la recuperación muscular.', 'Reduce el dolor post-ejercicio.', 'Repone electrolitos.', 'Neutraliza el efecto catabólico.'],
    keyIngredients: ['Aminoácidos (BCAAs, Glutamina)', 'Agua de Coco', 'Antioxidantes', 'Granada'],
    suggestedUsage: 'Tomar 1 stick disuelto en agua inmediatamente después del ejercicio.',
    expectedResults: 'Recuperación muscular más rápida y efectiva, menor fatiga y dolor muscular.',
    imageUrl: '/assets/images/post_sport.png',
    videoUrl: '/assets/videos/post_sport.mp4',
    tags: ['deporte', 'rendimiento deportivo', 'post-entreno', 'recuperación', 'músculos', 'dolor muscular', 'bcaas', 'glutamina'],
  },
  {
    id: 'biopro_sport',
    name: 'Biopro+ Sport',
    price: 35.45,
    points: 16,
    category: 'Rendimiento Deportivo',
    description: 'Delicioso batido proteico instantáneo con sabor a vainilla, a base de Bioprotein con Colostrum y Actinos.',
    benefits: ['Promueve la generación de masa muscular magra.', 'Mejora el desempeño y la recuperación física.', 'Evita el desgaste.', 'Incrementa el flujo sanguíneo al músculo.'],
    keyIngredients: ['Bioprotein+ con Colostrum®', 'Actinos®', 'Aminoácidos'],
    suggestedUsage: 'Tomar 1 stick disuelto en agua después del ejercicio o como snack proteico.',
    expectedResults: 'Aumento de la masa muscular, mejor rendimiento y una recuperación optimizada.',
    imageUrl: '/assets/images/biopro_sport.png',
    videoUrl: '/assets/videos/biopro_sport.mp4',
    tags: ['deporte', 'rendimiento deportivo', 'proteína', 'masa muscular', 'fuerza', 'colostrum', 'actinos'],
  },
  {
    id: 'protein_active_sport',
    name: 'Protein Active Sport',
    price: 46.25,
    points: 20,
    category: 'Rendimiento Deportivo',
    description: 'Proteína activa de origen 100% vegetal que promueve la regeneración celular y el desarrollo saludable de la masa muscular.',
    benefits: ['Promueve la regeneración celular.', 'Ayuda al desarrollo de la masa muscular.', 'Apto para veganos y vegetarianos.'],
    keyIngredients: ['Proteína Germinada (Bioprotein Active®)'],
    suggestedUsage: 'Tomar 1 stick disuelto en agua o bebida vegetal después del ejercicio.',
    expectedResults: 'Mejores resultados en menor tiempo, recuperación mejorada y desarrollo muscular.',
    imageUrl: '/assets/images/protein_active_sport.png',
    videoUrl: '/assets/videos/protein_active_sport.mp4',
    tags: ['deporte', 'rendimiento deportivo', 'proteína', 'vegetal', 'vegano', 'masa muscular', 'regeneración'],
  },

  // LÍNEA GASTRONÓMICA
  {
    id: 'probix',
    name: 'Probix',
    price: 41.00,
    points: 20,
    category: 'Gastronómica y Nutrición',
    description: 'La nueva combinación de probióticos listos con sales naturales, para espolvorear sobre tus comidas.',
    benefits: ['Ayuda a regular el metabolismo.', 'Reduce la medida del abdomen.', 'Mejora la salud digestiva de forma práctica.'],
    keyIngredients: ['Probióticos (10 mil millones)', 'Sales Naturales'],
    suggestedUsage: 'Espolvorear 1 sobre sobre tus comidas frías o tibias.',
    expectedResults: 'Mejora del metabolismo y la digestión, ayudando a reducir medidas abdominales.',
    imageUrl: '/assets/images/probix.png',
    videoUrl: '/assets/videos/probix.mp4',
    tags: ['gastronómica', 'probióticos', 'metabolismo', 'abdomen', 'digestión', 'comidas'],
  },
  {
    id: 'qocina_fuxion',
    name: 'Q\'ocina Fuxion',
    price: 6.90,
    category: 'Gastronómica y Nutrición',
    description: 'Las nuevas Bases Madre Q\'ocina en Casa son preparaciones culinarias que concentran lo mejor de nuestra cocina.',
    benefits: ['Bases 100% naturales para cocinar.', 'Sin saborizantes ni conservantes artificiales.', 'Aportan sabor y nutrientes a las comidas.'],
    keyIngredients: ['Vegetales Frescos', 'Abundantes y frescos cultivos peruanos.'],
    suggestedUsage: 'Usar como base para la preparación de una gran variedad de platos.',
    expectedResults: 'Platos con un sabor delicioso, saludable y natural.',
    imageUrl: '/assets/images/qocina_fuxion.png',
    videoUrl: '/assets/videos/qocina_fuxion.mp4',
    tags: ['gastronómica', 'cocina', 'saludable', 'natural', 'base madre', 'sabor', 'aderezo'],
  },

  // SISTEMA BASE (Limpieza, Regeneración, Revitalización)
  {
    id: 'prunex_1',
    name: 'Prunex 1',
    price: 41.00,
    points: 20,
    category: 'Desintoxicación y Limpieza',
    description: 'Té herbal a base de mix de fibras solubles, una alternativa eficaz en casos de malestar por tránsito intestinal lento.',
    benefits: ['Promueve la regularidad del tránsito intestinal.', 'Alivia el estreñimiento.', 'Limpia el colon de manera efectiva.'],
    keyIngredients: ['Mix de Fibras (Psyllium, Inulina)', 'Extracto de Guindón', 'Kelp', 'Anís Estrella'],
    suggestedUsage: 'Tomar 1 stick disuelto en agua caliente por la noche, antes de dormir.',
    expectedResults: 'Alivio del estreñimiento y limpieza intestinal profunda en 8-10 horas.',
    imageUrl: '/assets/images/prunex_1.png',
    videoUrl: '/assets/videos/prunex_1.mp4',
    tags: ['limpieza', 'desintoxicación', 'digestión', 'estreñimiento', 'colon', 'tránsito intestinal', 'fibra', 'prunex'],
  },
  {
    id: 'flora_liv',
    name: 'Flora Liv',
    price: 51.30,
    points: 25,
    category: 'Salud Digestiva',
    description: '10 mil millones de bacterias probióticas que potencian la flora probiótica para regenerar y proteger el sistema digestivo.',
    benefits: ['Regenera y equilibra la flora intestinal.', 'Fortalece el sistema inmunológico.', 'Mejora la digestión.'],
    keyIngredients: ['Probióticos (10 mil millones CFU)', 'Fibra Prebiótica', 'Pulpa de Granadilla'],
    suggestedUsage: 'Tomar 1 stick al día en agua fría, preferiblemente en ayunas.',
    expectedResults: 'Mejora digestiva, reducción de hinchazón y un sistema inmunológico más fuerte.',
    imageUrl: '/assets/images/flora_liv.png',
    videoUrl: '/assets/videos/flora_liv.mp4',
    tags: ['digestión', 'flora intestinal', 'probióticos', 'defensas', 'inmunológico', 'hinchazón', 'acidez'],
  },
  {
    id: 'alpha_balance',
    name: 'Alpha Balance',
    price: 51.30,
    points: 25,
    category: 'Desintoxicación y Limpieza',
    description: 'Bebida con base de vegetales verdes para la limpieza de órganos internos y desintoxicación de la sangre.',
    benefits: ['Equilibra el pH del organismo.', 'Limpia órganos y sangre.', 'Promueve la desintoxicación.', 'Fuente de antioxidantes.'],
    keyIngredients: ['Vegetales Verdes (Alfalfa, Chlorella, Espirulina)', 'Manzana Verde', 'Jengibre'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua, preferiblemente en ayunas.',
    expectedResults: 'Sensación de bienestar, más energía y un cuerpo más limpio y alcalino.',
    imageUrl: '/assets/images/alpha_balance.png',
    videoUrl: '/assets/videos/alpha_balance.mp4',
    tags: ['limpieza', 'desintoxicación', 'detox', 'ph', 'alcalino', 'sangre', 'vegetales verdes', 'energía'],
  },
  {
    id: 'liquid_fiber',
    name: 'Liquid Fiber',
    price: 41.00,
    points: 20,
    category: 'Salud Digestiva',
    description: 'Deliciosa bebida con fibra soluble y micronutrientes que nutren y protegen la flora intestinal para promover la puntualidad en el tránsito intestinal.',
    benefits: ['Promueve la regularidad del tránsito intestinal.', 'Nutre la flora intestinal (prebiótico).', 'Ayuda a controlar el peso al dar saciedad.'],
    keyIngredients: ['Fibra Soluble (Inulina)', 'Micronutrientes'],
    suggestedUsage: 'Tomar 1 stick al día disuelto en agua.',
    expectedResults: 'Tránsito intestinal regular y una mejor salud digestiva general.',
    imageUrl: '/assets/images/liquid_fiber.png',
    videoUrl: '/assets/videos/liquid_fiber.mp4',
    tags: ['digestión', 'fibra', 'prebiótico', 'tránsito intestinal', 'regularidad', 'saciedad'],
  },
  {
    id: 'berry_balance',
    name: 'Berry Balance',
    price: 51.30,
    points: 25,
    category: 'Salud Inmunológica',
    description: 'Deliciosa bebida de arándanos y super frutas exóticas para mantener saludable tu tracto urinario, prevenir infecciones y equilibrar tu pH.',
    benefits: ['Previene infecciones del tracto urinario (ITU).', 'Equilibra el pH del sistema urinario.', 'Potente efecto antioxidante.', 'Ayuda a eliminar retención de líquidos.'],
    keyIngredients: ['Extracto de Cranberry', 'Blueberry', 'Camu Camu', 'Infusión de Piña'],
    suggestedUsage: 'Tomar 1 o 2 sticks al día disueltos en agua.',
    expectedResults: 'Protección y limpieza del sistema urinario, reduciendo la recurrencia de molestias.',
    imageUrl: '/assets/images/berry_balance.png',
    videoUrl: '/assets/videos/berry_balance.mp4',
    tags: ['urinario', 'infecciones urinarias', 'itu', 'riñones', 'arándanos', 'cranberry', 'retención de líquidos', 'defensas'],
  },
  {
    id: 'rexet',
    name: 'Rexet',
    price: 41.00,
    points: 20,
    category: 'Desintoxicación y Limpieza',
    description: 'Deliciosa bebida efervescente que ayuda a proteger y potenciar el hígado gracias a su mix nutracéutico.',
    benefits: ['Protege y desintoxica el hígado.', 'Promueve la función depurativa del organismo.', 'Ayuda a recuperarse de excesos.'],
    keyIngredients: ['Extractos Vegetales (Alcachofa, Perejil)', 'Vitaminas', 'Minerales', 'Taurina'],
    suggestedUsage: 'Tomar 1 stick al día, disuelto en agua, después de comidas pesadas o por la noche.',
    expectedResults: 'Mejora en la función hepática y una sensación general de limpieza y bienestar.',
    imageUrl: '/assets/images/rexet.png',
    videoUrl: '/assets/videos/rexet.mp4',
    tags: ['limpieza', 'desintoxicación', 'hígado', 'depurativo', 'excesos', 'resaca'],
  },
  {
    id: 'biopro_tect',
    name: 'Biopro Tect+',
    price: 35.45,
    points: 16,
    category: 'Salud Inmunológica',
    description: 'Fórmula patentada de Fuxion que eleva cualitativa y cuantitativamente el perfil proteico de la dieta diaria y potencia el sistema de defensas.',
    benefits: ['Potencia el sistema de defensas.', 'Eleva el perfil proteico de la dieta.', 'Fortalece los huesos.', 'Mejora la regeneración celular.'],
    keyIngredients: ['Bioprotein+ con Colostrum®', 'Bioferrín®', 'Calcio Lácteo', 'DHA y ARA'],
    suggestedUsage: 'Tomar 1 stick al día disuelto en la bebida de preferencia.',
    expectedResults: 'Sistema de defensas fortalecido y una mejor nutrición general.',
    imageUrl: '/assets/images/biopro_tect.png',
    videoUrl: '/assets/videos/biopro_tect.mp4',
    tags: ['regeneración', 'defensas', 'inmunológico', 'proteína', 'huesos', 'nutrición', 'colostrum', 'niños', 'familia'],
  },
  {
    id: 'protein_active',
    name: 'Protein Active',
    price: 46.25,
    points: 20,
    category: 'Gastronómica y Nutrición',
    description: 'Proteína activa de origen 100% vegetal de buena asimilación que complementa perfectamente tu alimentación diaria.',
    benefits: ['Complementa la alimentación con proteína de alta calidad.', '100% vegetal, apta para veganos.', 'Mejora la regeneración celular.'],
    keyIngredients: ['Bioprotein Active® (Proteína de Arveja, Arroz Integral Germinado, Quinua Germinada, Algas)'],
    suggestedUsage: 'Tomar 1 stick disuelto en agua o bebida vegetal.',
    expectedResults: 'Nutrición completa y balanceada, ideal para complementar cualquier dieta.',
    imageUrl: '/assets/images/protein_active.png',
    videoUrl: '/assets/videos/protein_active.mp4',
    tags: ['regeneración', 'proteína', 'vegetal', 'vegano', 'nutrición', 'dieta'],
  },
  {
    id: 'vita_xtra_t',
    name: 'Vita Xtra T+',
    price: 41.00,
    points: 20,
    category: 'Energía y Vitalidad',
    description: 'Bebida rica en antioxidantes y energizantes a partir de extractos frutales y el acai berry, guayusa, y té verde.',
    benefits: ['Proporciona energía y vitalidad por más tiempo.', 'Potente efecto antioxidante.', 'Mejora el ánimo y la concentración.', 'Disipa la fatiga.'],
    keyIngredients: ['Té Verde', 'Acai Berry', 'Guayusa', 'Maca', 'Goji Berry', 'Maíz Morado'],
    suggestedUsage: 'Tomar 1 stick por la mañana o cuando se necesite un impulso de energía.',
    expectedResults: 'Día lleno de energía, vitalidad y con un estado de ánimo positivo.',
    imageUrl: '/assets/images/vita_xtra_t.png',
    videoUrl: '/assets/videos/vita_xtra_t.mp4',
    tags: ['energía', 'vitalidad', 'revitalizar', 'antioxidante', 'fatiga', 'cansancio', 'concentración', 'mañana'],
  },
  {
    id: 'nutraday',
    name: 'Nutraday',
    price: 41.00,
    points: 20,
    category: 'Energía y Vitalidad',
    description: 'Delicioso refresco sabor a fresa natural con micronutrientes para tener más vitalidad y fortalecer sus defensas.',
    benefits: ['Complementa la nutrición diaria.', 'Fortalece el sistema inmunológico.', 'Promueve un óptimo desarrollo físico y mental.', 'Fuente natural de hierro y calcio.'],
    keyIngredients: ['Extracto de Moringa', 'Guayaba', 'Limón', 'Albahaca', 'Camu Camu', '12 Vitaminas y 5 Minerales'],
    suggestedUsage: 'Tomar 1 stick al día, ideal para toda la familia.',
    expectedResults: 'Mayor vitalidad y defensas más fuertes para toda la familia.',
    imageUrl: '/assets/images/nutraday.png',
    videoUrl: '/assets/videos/nutraday.mp4',
    tags: ['energía', 'revitalizar', 'familia', 'niños', 'vitaminas', 'minerales', 'defensas', 'nutrición', 'moringa'],
  },

  // LÍNEA INMUNOLÓGICA
  {
    id: 'vera',
    name: 'Vera+',
    price: 51.30,
    points: 25,
    category: 'Salud Inmunológica',
    description: 'Delicioso té de menta con Aloe Vera y AMALAKI, enriquecido con las fórmulas patentadas Wellmune WGP y Oliactive.',
    benefits: ['Refuerza el sistema inmunológico.', 'Ayuda a prevenir alergias.', 'Potente efecto antiviral y antibacteriano.'],
    keyIngredients: ['Aloe Vera', 'AMALAKI', 'Wellmune WGP', 'Oliactive', 'Bioferrin'],
    suggestedUsage: 'Tomar 1 stick al día disuelto en agua.',
    expectedResults: 'Sistema inmunológico más fuerte y resistente a enfermedades.',
    imageUrl: '/assets/images/vera.png',
    videoUrl: '/assets/videos/vera.mp4',
    tags: ['inmunológico', 'defensas', 'alergias', 'gripe', 'virus', 'wellmune', 'aloe vera'],
  },
  {
    id: 'ganomas_capuccino',
    name: 'Ganomas Capuccino',
    price: 23.65,
    points: 10,
    category: 'Salud Inmunológica',
    description: 'Delicioso café capuccino elaborado con extracto de Ganoderma Lucidum, el hongo de la longevidad.',
    benefits: ['Modula las defensas del organismo.', 'Ayuda a prevenir la proliferación de células malignas.', 'Gran poder antioxidante.'],
    keyIngredients: ['Extracto de Ganoderma Lucidum'],
    suggestedUsage: 'Disfrutar de 1 stick al día como un café capuccino saludable.',
    expectedResults: 'Un sistema de defensas modulado y una protección celular superior.',
    imageUrl: '/assets/images/ganomas_capuccino.png',
    videoUrl: '/assets/videos/ganomas_capuccino.mp4',
    tags: ['inmunológico', 'defensas', 'cáncer', 'antioxidante', 'ganoderma', 'café', 'capuccino'],
  },

  // LÍNEA CONTROL DE PESO
  {
    id: 'thermo_t3',
    name: 'Thermo T3',
    price: 41.00,
    points: 20,
    category: 'Control de Peso',
    description: 'Delicioso mix de tres tés, con limón y extractos vegetales que promueven un óptimo metabolismo.',
    benefits: ['Genera energía a partir de la grasa acumulada.', 'Aumenta la resistencia.', 'Reduce la acumulación de grasas.', 'Acelera el metabolismo.'],
    keyIngredients: ['Mix de Tés (Rojo, Negro, Verde)', 'L-Carnitina', 'Tamarindo Malabar'],
    suggestedUsage: 'Tomar 1 stick antes del ejercicio o por la mañana.',
    expectedResults: 'Reducción de medidas y un metabolismo más activo.',
    imageUrl: '/assets/images/thermo_t3.png',
    videoUrl: '/assets/videos/thermo_t3.mp4',
    tags: ['control de peso', 'quemar grasa', 'metabolismo', 'medidas', 'energía', 'té', 'gimnasio'],
  },
  {
    id: 'nocarb_t',
    name: 'Nocarb T',
    price: 41.00,
    points: 20,
    category: 'Control de Peso',
    description: 'Su fórmula rica en Fibras Solubles, Cromo y Té Verde que ayudarán a reducir la elevación de los niveles de glucosa en la sangre.',
    benefits: ['Reduce la asimilación de carbohidratos y azúcares.', 'Ayuda a controlar los niveles de glucosa en sangre.', 'Reduce la acumulación de grasa.'],
    keyIngredients: ['Fibras Solubles', 'Cromo', 'Té Verde'],
    suggestedUsage: 'Tomar 1 stick antes de las comidas altas en carbohidratos.',
    expectedResults: 'Mejor control de la glucosa y menor impacto de los carbohidratos en el peso.',
    imageUrl: '/assets/images/nocarb_t.png',
    videoUrl: '/assets/videos/nocarb_t.mp4',
    tags: ['control de peso', 'carbohidratos', 'azúcar', 'glucosa', 'diabetes', 'insulina', 'fibra'],
  },
  {
    id: 'chocolate_fit',
    name: 'Chocolate Fit',
    price: 28.75,
    points: 12,
    category: 'Control de Peso',
    description: 'Deliciosa bebida de origen 100% vegetal hecha a base de chocolate negro del Amazonas, crema no láctea y CLA.',
    benefits: ['Ayuda a reducir la sensación de apetito (antojos).', 'Contribuye a la reducción de medidas.', 'Aporta un gusto sin culpas.'],
    keyIngredients: ['Chocolate Negro del Amazonas', 'Crema no Láctea', 'CLA (Ácido Linoleico Conjugado)'],
    suggestedUsage: 'Tomar 1 stick como un snack saludable entre comidas.',
    expectedResults: 'Reducción de antojos y apoyo en el plan de control de peso.',
    imageUrl: '/assets/images/chocolate_fit.png',
    videoUrl: '/assets/videos/chocolate_fit.mp4',
    tags: ['control de peso', 'antojos', 'ansiedad por comer', 'chocolate', 'saciedad', 'cla'],
  },
  {
    id: 'biopro_fit',
    name: 'Biopro+ Fit',
    price: 35.45,
    points: 16,
    category: 'Control de Peso',
    description: 'Batido de proteínas a base de Bioprotein+ con Colostrum® y Prolibra®, que ayuda a acelerar el metabolismo y tonificar.',
    benefits: ['Acelera el metabolismo para quemar grasa.', 'Ayuda a tonificar los músculos.', 'Reduce la sensación de apetito.', 'Mejora la nutrición general.'],
    keyIngredients: ['Bioprotein+ con Colostrum®', 'Prolibra®', 'CLA', 'Aminoácidos'],
    suggestedUsage: 'Tomar 1 stick después del ejercicio o como reemplazo de una cena.',
    expectedResults: 'Músculos más tonificados y un porcentaje de grasa corporal reducido.',
    imageUrl: '/assets/images/biopro_fit.png',
    videoUrl: '/assets/videos/biopro_fit.mp4',
    tags: ['control de peso', 'proteína', 'tonificar', 'músculos', 'metabolismo', 'saciedad', 'prolibra'],
  },
  {
    id: 'protein_active_fit',
    name: 'Protein Active Fit',
    price: 46.25,
    points: 20,
    category: 'Control de Peso',
    description: 'Proteína 100% vegetal de buena asimilación, con CLA, Vitaminas del Complejo B que promueven el metabolismo de las grasas.',
    benefits: ['Promueve un metabolismo de grasas saludable.', 'Ideal para dietas veganas o vegetarianas.', 'Ayuda a tonificar mientras se controla el peso.'],
    keyIngredients: ['Proteína 100% Vegetal (Bioprotein Active®)', 'CLA', 'Vitaminas del Complejo B'],
    suggestedUsage: 'Tomar 1 stick como snack o después del ejercicio.',
    expectedResults: 'Apoyo en la pérdida de peso y tonificación muscular, en un formato 100% vegetal.',
    imageUrl: '/assets/images/protein_active_fit.png',
    videoUrl: '/assets/videos/protein_active_fit.mp4',
    tags: ['control de peso', 'proteína', 'vegetal', 'vegano', 'tonificar', 'metabolismo', 'cla'],
  },
];



export const FORM_STEPS: FormStep[] = [
  { 
    id: 1, 
    name: 'Información Personal', 
    fields: ['name', 'age', 'gender', 'phone', 'email', 'occupation', 'activityLevel'] 
  },
  { 
    id: 2, 
    name: 'Objetivo Principal de Bienestar', 
    fields: ['mainGoal', 'priorityGoalDetails'] 
  },
  { 
    id: 3, 
    name: 'Hábitos de Estilo de Vida', 
    fields: ['dietType', 'customDietType', 'mealRegularity', 'waterIntake', 'exerciseFrequency', 'exerciseType', 'sleepHours', 'sleepQuality'] 
  },
  { 
    id: 4, 
    name: 'Salud General y Síntomas', 
    fields: ['commonSymptoms', 'medicalConditions', 'currentMedications', 'additionalInfo'] 
  },
];