[build]
  publish = "dist"
  command = "npm run build"

[[forms]]
  name = "fuxion_reco_form" # Este nombre debe coincidir EXACTAMENTE con el 'name' de tu <form>
  # Puedes añadir una acción de redirección después del envío si lo deseas
  # action = "/gracias" # Por ejemplo, una página 'gracias.html'

  # Si quieres especificar los campos explícitamente (opcional, Netlify los suele detectar)
  # fields = [
  #   { name = "name", type = "text" },
  #   { name = "email", type = "email" },
  #   { name = "phone", type = "text" },
  #   { name = "age", type = "number" },
  #   { name = "gender", type = "text" },
  #   { name = "occupation", type = "text" },
  #   { name = "activityLevel", type = "text" },
  #   { name = "dietType", type = "text" },
  #   { name = "customDietType", type = "text" },
  #   { name = "mealRegularity", type = "text" },
  #   { name = "waterIntake", type = "text" },
  #   { name = "exerciseFrequency", type = "text" },
  #   { name = "exerciseType", type = "text" },
  #   { name = "sleepHours", type = "number" },
  #   { name = "sleepQuality", type = "text" },
  #   { name = "commonSymptoms", type = "text[]" }, # Para múltiples selecciones (checkboxes)
  #   { name = "medicalConditions", type = "text" },
  #   { name = "currentMedications", type = "text" },
  #   { name = "additionalInfo", type = "text" }
  # ]